// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: streams/ivstream/investment_open.proto

package ivstream

import (
	proto "github.com/golang/protobuf/proto"
	common "github.com/huynguyen-quoc/go/streams/schema/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InvestmentOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message        string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	InvestmentId   int64              `protobuf:"varint,2,opt,name=investmentId,proto3" json:"investmentId,omitempty"`
	UserId         int64              `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	StreamMetadata *common.StreamInfo `protobuf:"bytes,1235,opt,name=StreamMetadata,proto3" json:"StreamMetadata,omitempty"`
}

func (message *InvestmentOpen) Reset() {
	*message = InvestmentOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streams_ivstream_investment_open_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(message))
		ms.StoreMessageInfo(mi)
	}
}

func (message *InvestmentOpen) String() string {
	return protoimpl.X.MessageStringOf(message)
}

func (*InvestmentOpen) ProtoMessage() {}

func (message *InvestmentOpen) ProtoReflect() protoreflect.Message {
	mi := &file_streams_ivstream_investment_open_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && message != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(message))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(message)
}

// Deprecated: Use InvestmentOpen.ProtoReflect.Descriptor instead.
func (*InvestmentOpen) Descriptor() ([]byte, []int) {
	return file_streams_ivstream_investment_open_proto_rawDescGZIP(), []int{0}
}

func (message *InvestmentOpen) GetMessage() string {
	if message != nil {
		return message.Message
	}
	return ""
}

func (message *InvestmentOpen) GetInvestmentId() int64 {
	if message != nil {
		return message.InvestmentId
	}
	return 0
}

func (message *InvestmentOpen) GetUserId() int64 {
	if message != nil {
		return message.UserId
	}
	return 0
}

func (message *InvestmentOpen) GetStreamMetadata() *common.StreamInfo {
	if message != nil {
		return message.StreamMetadata
	}
	return nil
}

var File_streams_ivstream_investment_open_proto protoreflect.FileDescriptor

var file_streams_ivstream_investment_open_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x69, 0x76, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x73, 0x2e, 0x69, 0x76, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x20, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a,
	0x0e, 0x49, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x76,
	0x65, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0xd3, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x75, 0x79, 0x6e, 0x67, 0x75, 0x79,
	0x65, 0x6e, 0x2d, 0x71, 0x75, 0x6f, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x69, 0x76, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_streams_ivstream_investment_open_proto_rawDescOnce sync.Once
	file_streams_ivstream_investment_open_proto_rawDescData = file_streams_ivstream_investment_open_proto_rawDesc
)

func file_streams_ivstream_investment_open_proto_rawDescGZIP() []byte {
	file_streams_ivstream_investment_open_proto_rawDescOnce.Do(func() {
		file_streams_ivstream_investment_open_proto_rawDescData = protoimpl.X.CompressGZIP(file_streams_ivstream_investment_open_proto_rawDescData)
	})
	return file_streams_ivstream_investment_open_proto_rawDescData
}

var file_streams_ivstream_investment_open_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streams_ivstream_investment_open_proto_goTypes = []interface{}{
	(*InvestmentOpen)(nil),    // 0: streams.ivstream.InvestmentOpen
	(*common.StreamInfo)(nil), // 1: streams.common.StreamInfo
}
var file_streams_ivstream_investment_open_proto_depIdxs = []int32{
	1, // 0: streams.ivstream.InvestmentOpen.StreamMetadata:type_name -> streams.common.StreamInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_streams_ivstream_investment_open_proto_init() }
func file_streams_ivstream_investment_open_proto_init() {
	if File_streams_ivstream_investment_open_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_streams_ivstream_investment_open_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvestmentOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_streams_ivstream_investment_open_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streams_ivstream_investment_open_proto_goTypes,
		DependencyIndexes: file_streams_ivstream_investment_open_proto_depIdxs,
		MessageInfos:      file_streams_ivstream_investment_open_proto_msgTypes,
	}.Build()
	File_streams_ivstream_investment_open_proto = out.File
	file_streams_ivstream_investment_open_proto_rawDesc = nil
	file_streams_ivstream_investment_open_proto_goTypes = nil
	file_streams_ivstream_investment_open_proto_depIdxs = nil
}
