// Code generated by mockery v2.2.1. DO NOT EDIT.

package core

import mock "github.com/stretchr/testify/mock"

// MockWriterDTO is an autogenerated mock type for the WriterDTO type
type MockWriterDTO struct {
	mock.Mock
}

// ToProtoBuf provides a mock function with given fields: isUpdate
func (_m *MockWriterDTO) ToProtoBuf(isUpdate bool) Message {
	ret := _m.Called(isUpdate)

	var r0 Message
	if rf, ok := ret.Get(0).(func(bool) Message); ok {
		r0 = rf(isUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Message)
		}
	}

	return r0
}
