// Code generated by mockery v2.2.1. DO NOT EDIT.

package core

import mock "github.com/stretchr/testify/mock"

// MockStreamConsumer is an autogenerated mock type for the StreamConsumer type
type MockStreamConsumer struct {
	mock.Mock
}

// Done provides a mock function with given fields:
func (_m *MockStreamConsumer) Done() <-chan struct{} {
	ret := _m.Called()

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// GetDataChan provides a mock function with given fields:
func (_m *MockStreamConsumer) GetDataChan() <-chan ConsumerMessage {
	ret := _m.Called()

	var r0 <-chan ConsumerMessage
	if rf, ok := ret.Get(0).(func() <-chan ConsumerMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ConsumerMessage)
		}
	}

	return r0
}

// Shutdown provides a mock function with given fields:
func (_m *MockStreamConsumer) Shutdown() {
	_m.Called()
}

// Start provides a mock function with given fields:
func (_m *MockStreamConsumer) Start() {
	_m.Called()
}
