// Code generated by mockery v2.2.1. DO NOT EDIT.

package kafka

import (
	context "context"

	core "github.com/huynguyen-quoc/go/streams/core"
	mock "github.com/stretchr/testify/mock"
)

// MockConsumerInitialization is an autogenerated mock type for the ConsumerInitialization type
type MockConsumerInitialization struct {
	mock.Mock
}

// NewKafkaConsumer provides a mock function with given fields: ctx
func (_m *MockConsumerInitialization) NewKafkaConsumer(ctx context.Context) (core.StreamConsumer, error) {
	ret := _m.Called(ctx)

	var r0 core.StreamConsumer
	if rf, ok := ret.Get(0).(func(context.Context) core.StreamConsumer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.StreamConsumer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
