// Code generated by mockery v2.2.1. DO NOT EDIT.

package kafka

import (
	context "context"

	config "github.com/huynguyen-quoc/go/streams/kafka/config"

	core "github.com/huynguyen-quoc/go/streams/core"

	mock "github.com/stretchr/testify/mock"
)

// MockProducerInitialization is an autogenerated mock type for the ProducerInitialization type
type MockProducerInitialization struct {
	mock.Mock
}

// NewKafkaProducer provides a mock function with given fields: ctx, kafkaConfig, streamID
func (_m *MockProducerInitialization) NewKafkaProducer(ctx context.Context, kafkaConfig config.KafkaConfig, streamID string) (core.StreamProducer, error) {
	ret := _m.Called(ctx, kafkaConfig, streamID)

	var r0 core.StreamProducer
	if rf, ok := ret.Get(0).(func(context.Context, config.KafkaConfig, string) core.StreamProducer); ok {
		r0 = rf(ctx, kafkaConfig, streamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.StreamProducer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, config.KafkaConfig, string) error); ok {
		r1 = rf(ctx, kafkaConfig, streamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
