// Code generated by mockery v2.2.1. DO NOT EDIT.

package kafka

import (
	config "github.com/huynguyen-quoc/go/streams/kafka/config"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigurer is an autogenerated mock type for the Configurer type
type MockConfigurer struct {
	mock.Mock
}

// GetConfig provides a mock function with given fields:
func (_m *MockConfigurer) GetConfig() config.KafkaConfig {
	ret := _m.Called()

	var r0 config.KafkaConfig
	if rf, ok := ret.Get(0).(func() config.KafkaConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.KafkaConfig)
	}

	return r0
}

// GetStreamID provides a mock function with given fields:
func (_m *MockConfigurer) GetStreamID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
