// Code generated by mockery v2.2.1. DO NOT EDIT.

package kafkareader

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// Done provides a mock function with given fields:
func (_m *MockClient) Done() <-chan struct{} {
	ret := _m.Called()

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// GetDataChan provides a mock function with given fields:
func (_m *MockClient) GetDataChan() <-chan *Entity {
	ret := _m.Called()

	var r0 <-chan *Entity
	if rf, ok := ret.Get(0).(func() <-chan *Entity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *Entity)
		}
	}

	return r0
}

// Shutdown provides a mock function with given fields:
func (_m *MockClient) Shutdown() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
